### ISSUE TITLE
Request: Add support for Video block

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#13]
Requesting support for the `video` block:
https://api.slack.com/reference/block-kit/blocks#video

TODO: https://github.com/themashcodee/slack-blocks-to-jsx/blob/9d462cad3719baa2ef7ed85f5243d5c1cfb6616a/src/components/blocks/video.tsx#L4

**Comment by themashcodee** [comment]
@StephenTangCook Added in v0.3.1
