### ISSUE TITLE
Allow emoji hook to return ReactNode

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#17]
When replacing custom Slack emojis, the html/react used will likely need to be an image component. Thus, the `emoji` hook function should return a `ReactNode` like the others:
https://github.com/themashcodee/slack-blocks-to-jsx/blob/14721fc54a9a707028d8aad3558f67e571e88979/src/store/useGlobalData.ts#L26

Also, a small nit but you rename the `emoji_text` arg to something like `shortcode` or `name` to more accurately represent its function.

**Comment by StephenTangCook** [comment]
Is there a way to fallback to the default behavior? 
For example, let's say I have a `hook` with custom logic to replace an emoji. But if I fail to find that custom emoji in my system, I'd just want to fallback to the original behavior of this library for replacing emojis.

**Comment by themashcodee** [comment]
> Is there a way to fallback to the default behavior? For example, let's say I have a `hook` with custom logic to replace an emoji. But if I fail to find that custom emoji in my system, I'd just want to fallback to the original behavior of this library for replacing emojis.

Yeah I will add that option.

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.3.7](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.3.7)

**Comment by themashcodee** [comment]
here is how you can use the fallback @StephenTangCook 
<img width="994" alt="Screenshot 2024-07-12 at 12 09 55 AM" src="https://github.com/themashcodee/slack-blocks-to-jsx/assets/50915748/d53a37fb-1522-47ad-a639-bbd9db179b5b">
