### ISSUE TITLE
More precise Slack emoji regex

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#18]
Slack emoji names must be lowercase, and can’t contain spaces, periods, or most punctuation. Generally the regex pattern is `:([a-zA-Z0-9_\-+']+):`.

Can replace:
https://github.com/themashcodee/slack-blocks-to-jsx/blob/99de83798ea13f0dbebd42d3b3d54a29d1266c70/src/utils/markdown_parser/tokenizers/slack_emoji/parse.ts#L13

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.3.10](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.3.10)
