### ISSUE TITLE
Rich text section element class string has unnecessary whitespace

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#19]
The rich text section element class string produces a lot of unnecessary whitespace. We should use a tool like `dedent` to remove the extra whitespace.

https://github.com/themashcodee/slack-blocks-to-jsx/blob/853e8b1c451ad41f51b11e1b8e71c7d6601b8db3/src/components/blocks/rich_text/rich_text_section.tsx#L27-L33

![Screenshot 2024-07-12 at 6 28 50 PM](https://github.com/user-attachments/assets/69a2443e-3340-4a72-9e39-ac397993de64)

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.4.1](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.4.1)
