### ISSUE TITLE
Inconsistent left margins for nested lists

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#20]
There seems to be inconsistent left margins for nested ordered/unordered lists. Observe the consistent incremental left-margins displayed in Slack:

<img width="359" alt="Screenshot 2024-07-13 at 10 45 53 AM" src="https://github.com/user-attachments/assets/46bc90ec-1801-465f-b1fd-4d4c020bb7d1">

vs.
![Screenshot 2024-07-13 at 10 46 05 AM](https://github.com/user-attachments/assets/f842417f-6c04-40e4-912e-3d84e6b8fb7e)

![Screenshot 2024-07-13 at 10 46 39 AM](https://github.com/user-attachments/assets/e77501bc-4987-4304-9bbf-6af44ad0c9d8)

In particular the second row (white dot) has a larger jump.

Relevant code:
https://github.com/themashcodee/slack-blocks-to-jsx/blob/bead2079bf6757042f04584abd6a2516ac799789/src/components/blocks/rich_text/rich_text.tsx#L41

**Comment by themashcodee** [comment]
resolved in [v0.4.2](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.4.2)

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.4.2](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.4.2)
