### ISSUE TITLE
Layout styling is broken when withoutWrapper=true on <Message> component

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#21]
Left is `withoutWrapper=true`. The layout of child blocks are not in a column.
![Screenshot 2024-08-11 at 7 58 22 PM](https://github.com/user-attachments/assets/6381d7e3-c159-4ecf-b65b-4f8f412aeb2c)

**Comment by themashcodee** [comment]
@StephenTangCook please upgrade to https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.4.4, thanks for contributing 🙌🏼!
