### ISSUE TITLE
Unnecessary spacing between text elements in blockquotes

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#24]
Consecutive elements within blockquotes have unnecessary spacing between each other. For example, if you have **1***2*~3~, which are all separate consecutive rich text quote elements, they are spaced out instead of being next to each other.

 I believe this is caused by the `gap-2` on the blockquote element. Removing it fixes this specific case, but I'm not sure if it's there for other reasons.
https://github.com/themashcodee/slack-blocks-to-jsx/blob/ac98f06e8c9cddbf40b785a331f118087ef2ffa2/src/components/blocks/rich_text/rich_text.tsx#L115

**Example blocks:**
```js
[
    {
      "type": "rich_text",
      "block_id": "tUlwW",
      "elements": [
        {
          "type": "rich_text_quote",
          "elements": [
            {
              "type": "text",
              "text": "1",
              "style": {
                "bold": true
              }
            },
            {
              "type": "text",
              "text": "2",
              "style": {
                "italic": true
              }
            },
            {
              "type": "text",
              "text": "3",
              "style": {
                "strike": true
              }
            }
          ]
        }
      ]
    }
  ]
```
**Expected:**
<img width="75" alt="Screenshot 2024-08-12 at 9 06 12 AM" src="https://github.com/user-attachments/assets/20264618-87d6-4ec2-a2ac-878a4997bc3a">

(This is correctly what you get _without_ a blockquote)

**Actual:**
<img width="116" alt="Screenshot 2024-08-12 at 9 06 07 AM" src="https://github.com/user-attachments/assets/1dbceb76-b924-4802-b9eb-62449bd49988">

**Comment by themashcodee** [comment]
resolved in [0.5.0](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.0)
