### ISSUE TITLE
Images in `context` elements are too large

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#26]
`image` elements within `context` blocks are too large.

![Screenshot 2024-08-12 at 11 13 32 AM](https://github.com/user-attachments/assets/b40f64ce-bdc2-454c-9ec3-23bf30553e64)

**Expected:**

[Block Kit Builder example](https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22We%20found%20*205%20Hotels*%20in%20New%20Orleans,%20LA%20from%20*12/14%20to%2012/17*%22%7D,%22accessory%22:%7B%22type%22:%22overflow%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22emoji%22:true,%22text%22:%22Option%20One%22%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22emoji%22:true,%22text%22:%22Option%20Two%22%7D,%22value%22:%22value-1%22%7D%5D%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3CfakeLink.toHotelPage.com%7CWindsor%20Court%20Hotel%3E*%5Cn%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%85%5Cn$340%20per%20night%5CnRated:%209.4%20-%20Excellent%22%7D,%22accessory%22:%7B%22type%22:%22image%22,%22image_url%22:%22https://api.slack.com/img/blocks/bkb_template_images/tripAgent_1.png%22,%22alt_text%22:%22Windsor%20Court%20Hotel%20thumbnail%22%7D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22image%22,%22image_url%22:%22https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png%22,%22alt_text%22:%22Location%20Pin%20Icon%22%7D,%7B%22type%22:%22plain_text%22,%22emoji%22:true,%22text%22:%22Location:%20Central%20Business%20District%22%7D%5D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*%3CfakeLink.toHotelPage.com%7CThe%20Ritz-Carlton%20New%20Orleans%3E*%5Cn%E2%98%85%E2%98%85%E2%98%85%E2%98%85%E2%98%85%5Cn$340%20per%20night%5CnRated:%209.1%20-%20Excellent%22%7D,%22accessory%22:%7B%22type%22:%22image%22,%22image_url%22:%22https://api.slack.com/img/blocks/bkb_template_images/tripAgent_2.png%22,%22alt_text%22:%22Ritz-Carlton%20New%20Orleans%20thumbnail%22%7D%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22image%22,%22image_url%22:%22https://api.slack.com/img/blocks/bkb_template_images/tripAgentLocationMarker.png%22,%22alt_text%22:%22Location%20Pin%20Icon%22%7D,%7B%22type%22:%22plain_text%22,%22emoji%22:true,%22text%22:%22Location:%20French%20Quarter%22%7D%5D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22emoji%22:true,%22text%22:%22Learn%20More%22%7D,%22url%22:%22https://www.google.com/%22,%22value%22:%22click_me_123%22%7D%5D%7D%5D%7D)
![Screenshot 2024-08-12 at 11 15 38 AM](https://github.com/user-attachments/assets/33376823-be01-47fd-9647-873e78e8ed96)

**Comment by themashcodee** [comment]
resolved in [0.4.9](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.4.9)
