### ISSUE TITLE
Links in mrkdwn text elements are not shown

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#29]
Links within `mrkdwn` text, such as `<https://www.google.com|This is a link in mrkdwn>`, are not shown in the output.

[Block kit Builder example](https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22123%20*%3Chttps://www.google.com%7CThis%20is%20a%20link%20in%20mrkdwn%3E*%20456%22%7D%7D%5D%7D)
![Screenshot 2024-08-12 at 4 06 02 PM](https://github.com/user-attachments/assets/15ddb4f0-8a4c-4196-b34a-be3853b8e1f8)

Relevant code: https://github.com/themashcodee/slack-blocks-to-jsx/blob/59933bf0e5084419b1348ea6eecb286067e1295b/src/utils/markdown_parser/parser.tsx#L43

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [0.4.8](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.4.8)
