### ISSUE TITLE
Images always have same height and become squished on small screens

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#31]
![Screenshot 2024-08-15 at 10 45 56 AM](https://github.com/user-attachments/assets/3b0034c7-a1f4-45e6-8973-c14587d3bd3f)

Example block:
```
{
  "type": "image",
  "title": {
  "type": "plain_text",
  "text": "Breakfast included",
  "emoji": true
  },
  "image_url": "https://assets3.thrillist.com/v1/image/1682388/size/tl-horizontal_main.jpg",
  "alt_text": "breakfast"
}
```

**Comment by themashcodee** [comment]
@StephenTangCook I think it is already solved by this [commit](https://github.com/themashcodee/slack-blocks-to-jsx/commit/48646bdc22ec1fc3240d46d46210fb2d4cc21efd)
