### ISSUE TITLE
A11y Improvement: Use paragraph <p> tags for plain text

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#35]
For accessibility reasons, it is better to put text in <p> than in <div> or <span> where appropriate.

More info:
https://stackoverflow.com/a/67793924

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.5.4](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.4)
