### ISSUE TITLE
Bullet point is not vertically centered when the text contains inline code

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#36]
When you have a bulleted list with text containing `inline code`, the bullets are no longer centered.

[Block Kit Builder example](https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22type%22:%22rich_text%22,%22block_id%22:%22mBvrq%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22Test:%5Cn%22%7D%5D%7D,%7B%22type%22:%22rich_text_list%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20bullet%20point%20will%20look%20right%22%7D%5D%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22This%20one%20is%20not%20center%20aligned%20because%20of%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22inline%20code%22,%22style%22:%7B%22code%22:true%7D%7D%5D%7D%5D,%22style%22:%22bullet%22,%22indent%22:0,%22border%22:0%7D,%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%5D%7D%5D%7D%5D%7D)

![Screenshot 2024-08-18 at 9 44 17 PM](https://github.com/user-attachments/assets/39cd5303-eb01-410c-a4e2-64c94abe1b4a)

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.5.3](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.3)
