### ISSUE TITLE
Pass `style` through to custom hooks

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#37]
The `style` should be pass through on the rich text elements that have custom `hooks`, in case the caller wants to use the styles to affect their custom component.

Example:
For user mentions that are styled with italics, I would want the style
```
{
  "type": "user",
  "user_id": "U06V9T14762",
  "style": {
    "italic": true
  }
}
```

passed to:

https://github.com/themashcodee/slack-blocks-to-jsx/blob/429efa523c930813edc45ee42f0c7697dbed7723/src/components/blocks/rich_text/rich_text_section_user.tsx#L14

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.5.6](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.6)
