### ISSUE TITLE
Errors parsing mrkdwn that contains links with text and links without text

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#39]
There are parsing issues when a mrkdwn text object contains both links with text (e.g. `<https://www.google.com|My Link>`) _and_  links without text (e.g. `<https://www.google.com>`).

Example:
```
[
{
	"type": "context",
	"block_id": "6ZLaQ",
	"elements": [
		{
			"text": ":bulb: *Pro-tip* Curious how we created this message? You can use Slack's <https://app.slack.com/block-kit-builder|Block Kit Builder> to create complex message formats! Read more about blocks at <https://api.slack.com/block-kit>",
			"type": "mrkdwn"
		}
	]
}
]
```
![Screenshot 2024-08-25 at 1 58 19 PM](https://github.com/user-attachments/assets/81f4d2a3-2aa0-43d0-8bd0-a6d1bedd8460)

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.5.7](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.7)
