### ISSUE TITLE
Channel hook broken for channel tags in mrkdwn with names

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#41]
The Slack channel purpose and topic (aka Description and Topic) are returned by the Slack API as mrkdwn text. Note that the channel tags in this mrkdwn are in the format `<#C06420C2ZEA|channel-name>`. 

**Bug**: The channel hook in `hooks` passes in incorrect values for the tagged channel, where both `id` and `name` are in the form `C06420C2ZEA|channel-name`.

Here's an example:
[
<img width="724" alt="Screenshot 2024-09-10 at 5 18 42 PM" src="https://github.com/user-attachments/assets/0f345f73-3b7d-4a3d-a86a-93aeb4ba0669">
](url)

```
[
  {
    "text": {
      "text": "It’s a great spot for announcements and team-wide conversations.\n<@U060JP64TQA> is me! <#C060SL2H99U|general> is the name!! <!everyone>  <!here> <!channel> :test: :heart: :test_tube:123",
      "type": "mrkdwn"
    },
    "type": "section"
  }
]
```

My `channel` hook function is called and receives `id` = `C060SL2H99U|general`.

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.5.8](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.8)
