### ISSUE TITLE
Feature Request: Ability to configure links

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#43]
I have a use case where I want to wrap an entire Slack message blocks inside of an `<a>` tag. However if my Slack blocks happen to contain a link, the component converts it to an `<a>` tag, and NextJS gets angry that I have an `<a>` tag within an `<a>` tag (specifically there is a runtime hydration error because `<a>` cannot be a descendant of `<a>`).

Some potential resolutions:
1. Allow the consumer to configure whether links result in `<a>` tags (e.g. a boolean property on the config. When disabled, it wraps the URL in a `<span>` instead?
2. Add another `hook` for links, which is used whenever the component encounters a `link` object in rich-text blocks, or matches the link regex in `mrkdwn` objects.

**Comment by themashcodee** [comment]
@StephenTangCook added in [v0.5.9](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.5.9)
