### ISSUE TITLE
Support {ago} date format

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#44]
It appears Slack recently added the `{ago}` date format:
https://api.slack.com/reference/block-kit/blocks#date-element-type

This displays a relative time based on the current time. It would be useful to support this in the jsx component!

Example blocks:
https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%3C!date%5E1392734382%5EPosted%20%7Bago%7D%20on%20%7Bdate%7D.%7Cfallback%3E%22%7D%7D%5D%7D

**Comment by themashcodee** [comment]
Thanks @StephenTangCook for reporting this. I have added support for the new following formats

{ago}
{date_slash}
{day_divider_pretty}

in [v0.6.0](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.6.0)

Quick try out: https://slack-block-to-jsx-playground.vercel.app/
