### ISSUE TITLE
Links in `mrkdwn` text are displayed in markdown format

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#45]
URLs in `mrkdwn` elements in Slack blocks such as `<https://slack.com/help>` are appearing like `[https://slack.com/help](https://slack.com/help)`. 

[Block Kit Builder](https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22text%22:%7B%22text%22:%22A%20place%20to%20ask%20questions%20about%20all%20things%20Slack.%5Cn%5CnIf%20you%E2%80%99re%20looking%20for%20help%20getting%20started,%20check%20out%20our%20help%20center!%5Cn%5Cn%3Chttps://slack.com/help%3E%22,%22type%22:%22mrkdwn%22%7D,%22type%22:%22section%22%7D%5D%7D)

<img width="1132" alt="Screenshot 2024-10-28 at 1 43 33 PM" src="https://github.com/user-attachments/assets/fa01ef69-45db-45a7-b115-f1f8f126a73c">
<img width="1277" alt="Screenshot 2024-10-28 at 1 43 40 PM" src="https://github.com/user-attachments/assets/0888355d-b5a6-4373-9906-8211a75ec041">

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.6.1](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.6.1)
