### ISSUE TITLE
mrkdwn appearance regressions

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#46]
There appear to be a couple regressions caused in the latest releases:

1. There is excessive spacing for `\n` chars in mrkdwn text. It does not match the corresponding representation in Slack.
2. Links that appear in mrkdwn text were wrapped in `<a>`, but now are just raw text in a `<span>`.

[Block Kit](https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22text%22:%7B%22text%22:%22User%20(mention):%20%3C@U01000ADMIN%3E%5CnUser%20(non-existent):%20%3C@U0BOGUS%3E%5CnChannel:%20%3C#C123FULLINFO%7Cfull-info%3E%5CnChannel%20(non-existent):%20%3C#C0BOGUS%7Cbogus%3E%5Cn%3C!here%3E%5Cn%3C!channel%3E%5Cn%3C!everyone%3E%5Cn%3C!subteam%5ES062T6BLS4E%3E%5Cn:+1::skin-tone-5::smile::custom_emoji::custom_emoji_gif::alias_of_custom_emoji::alias_of_standard_heart::bogus_emoji:%5Cnhttps://www.test.com%22,%22type%22:%22mrkdwn%22%7D,%22type%22:%22section%22%7D%5D%7D)

![Screenshot 2024-11-02 at 12 33 02 PM](https://github.com/user-attachments/assets/abc9a7cd-2542-4a9d-bc7c-d0a721e71ce6)

**Comment by themashcodee** [comment]
@StephenTangCook Thanks for reporting, sorry about that, I think I messed up something. I will check it out. Thanks again!

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.6.3](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.6.3)
