### ISSUE TITLE
Ordered list numbering is not continued after indentations

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#47]
In an ordered list in rich text blocks, use an indented sub-list in the middle of the list. 
Expected: The numbering of the outer list continues after the sub-list
Actual: The numbering resets after the sub-list

[Block Kit Builder](https://app.slack.com/block-kit-builder#%7B%22blocks%22%3A%5B%7B%22type%22%3A%22rich_text%22%2C%22block_id%22%3A%22w9%2FLP%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_list%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%221%22%7D%5D%7D%2C%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22b%22%7D%5D%7D%2C%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22c%22%7D%5D%7D%5D%2C%22style%22%3A%22ordered%22%2C%22indent%22%3A0%2C%22border%22%3A0%7D%2C%7B%22type%22%3A%22rich_text_list%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22d%22%7D%5D%7D%2C%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22e%22%7D%5D%7D%5D%2C%22style%22%3A%22ordered%22%2C%22indent%22%3A1%2C%22border%22%3A0%7D%2C%7B%22type%22%3A%22rich_text_list%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22f%22%7D%5D%7D%2C%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22g%22%7D%5D%7D%5D%2C%22style%22%3A%22ordered%22%2C%22indent%22%3A0%2C%22offset%22%3A3%2C%22border%22%3A0%7D%2C%7B%22type%22%3A%22rich_text_list%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22h%22%7D%5D%7D%5D%2C%22style%22%3A%22ordered%22%2C%22indent%22%3A1%2C%22border%22%3A0%7D%2C%7B%22type%22%3A%22rich_text_list%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22i%22%7D%5D%7D%5D%2C%22style%22%3A%22ordered%22%2C%22indent%22%3A2%2C%22border%22%3A0%7D%2C%7B%22type%22%3A%22rich_text_list%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22rich_text_section%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22text%22%2C%22text%22%3A%22j%22%7D%5D%7D%5D%2C%22style%22%3A%22ordered%22%2C%22indent%22%3A0%2C%22offset%22%3A5%2C%22border%22%3A0%7D%5D%7D%5D%7D)

![Screenshot 2024-11-19 at 8 30 53 AM](https://github.com/user-attachments/assets/959b43c3-ae8c-4833-aa7a-ee1e966844b8)

**Comment by themashcodee** [comment]
@StephenTangCook resolved in [v0.6.4](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.6.4)

**Comment by StephenTangCook** [comment]
@themashcodee Thanks! Fast fix as usual!

**Comment by themashcodee** [comment]
@StephenTangCook ah I see, sorry for that. I only did it for indent:0, fixed in [v0.6.5](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.6.5)
