### ISSUE TITLE
Emoji parsing error when :emoji: is preceded by a colon

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#49]
When a Slack-style syntax `:emoji:` appears in mrkdwn, following some prefix that ends with a colon `:` and any whitespace (for example newlines `\n`), then the emoji does not get parsed and two extra colons are added to the result.
Example violating string:
```
Prefix::white_check_mark:
```

[Block Kit Builder example](https://app.slack.com/block-kit-builder/T060SL2GMU6#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Here's%20a%20checklist:%5Cn:white_check_mark:%20First%5Cn:white_check_mark:%20Second%5Cn:white_check_mark:%20Third%22%7D%7D%5D%7D)
<img width="1110" alt="Screenshot 2024-12-20 at 9 59 15 AM" src="https://github.com/user-attachments/assets/c14b127d-c1a0-49aa-b080-e28e24f59928" />

<img width="1271" alt="Screenshot 2024-12-20 at 9 59 03 AM" src="https://github.com/user-attachments/assets/21ca68a5-099b-4517-af44-b0c2e316ef47" />

**Comment by themashcodee** [comment]
@StephenTangCook For quick fix you can add a whitespace before `\n` until I push a proper fix.

**Comment by themashcodee** [comment]
@StephenTangCook fixed in [v0.6.7](https://github.com/themashcodee/slack-blocks-to-jsx/releases/tag/v0.6.7)
