### ISSUE TITLE
Emoji names library

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#7]
https://github.com/themashcodee/slack-blocks-to-jsx/blob/9d462cad3719baa2ef7ed85f5243d5c1cfb6616a/src/utils/emojis.ts#L5

For reference, Slack uses the emoji library https://github.com/iamcal/emoji-data (source: https://api.slack.com/reference/surfaces/formatting#emoji). It's not a good idea to try to fill in the "missing emojis" from the node-emoji library as Slack will have a large number of different names in their naming system.

**Comment by themashcodee** [comment]
Hey @StephenTangCook, Thanks for raising this issue.

You are correct, I should use https://github.com/nulab/emoji-data-ts to parse emojis as it is based on slack emoji data.

**Comment by themashcodee** [comment]
resolved in v0.3.3
